/*
 * Huawei Network Slice Management NBI
 * Author: Kevin McDonnell kwx420965
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SliceCatalogApi
 */
@Ignore
public class SliceCatalogApiTest {

    private final SliceCatalogApi api = new SliceCatalogApi();

    
    /**
     * Query  Slice Template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void nmsfSlicecatalogV1TemplatesGetTest() throws ApiException {
        String xAuthToken = null;
        api.nmsfSlicecatalogV1TemplatesGet(xAuthToken);

        // TODO: test validations
    }
    
}
